- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  wikiLink: "https://wiki.ss14.su/%D0%A5%D0%B8%D0%BC%D0%B8%D0%BA"
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 9000
  startingGear: ChemistGear
  icon: "Chemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: ChemistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChemistry
    back: ClothingBackpackChemistryFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLabChem
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    pocket1: HandLabeler
    # the purple glasses?
  innerclothingskirt: ClothingUniformJumpskirtChemistry
  satchel: ClothingBackpackSatchelChemistryFilled
  duffelbag: ClothingBackpackDuffelChemistryFilled
