# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  wikiLink: "https://wiki.ss14.su/%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D1%8B%D0%B9_%D0%92%D1%80%D0%B0%D1%87"
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 6000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 15000
  weight: 10
  startingGear: CMOGear
  icon: "ChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  whitelistedSpecies:
    - Human
    - Dwarf
  canBeAntag: true
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer

- type: startingGear
  id: CMOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLabCmo
    id: CMOPDA
    ears: ClothingHeadsetAltMedical
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtCMO
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
