- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  wikiLink: "https://wiki.ss14.su/%D0%9A%D0%B0%D0%BF%D0%B8%D1%82%D0%B0%D0%BD"
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 27000
    - !type:OverallPlaytimeRequirement
      time: 162000
  weight: 20
  startingGear: CaptainGear
  icon: "Captain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
  whitelistedSpecies:
    - Human
  accessGroups:
  - AllAccess

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerclothingskirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
