- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  wikiLink: "https://wiki.ss14.su/%D0%9A%D0%B0%D0%B4%D0%B5%D1%82"
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 9000
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000
      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "SecurityCadet"
  supervisors: job-supervisors-security
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
  whitelistedSpecies:
    - Human
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance

- type: startingGear
  id: SecurityCadetGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
  innerclothingskirt: ClothingUniformJumpskirtColorRed
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
