- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  wikiLink: "https://wiki.ss14.su/%D0%A1%D1%82%D0%B0%D1%80%D1%88%D0%B8%D0%B9_%D0%98%D0%BD%D0%B6%D0%B5%D0%BD%D0%B5%D1%80"
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 6000
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 27000
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "ChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  whitelistedSpecies:
    - Human
    - Dwarf
  canBeAntag: true
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics

- type: startingGear
  id: ChiefEngineerGear
  equipment:
    head: ClothingHeadHatHardhatWhite
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesColorBrown
    id: CEPDA
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
    belt: ClothingBeltChiefEngineerFilled
  innerclothingskirt: ClothingUniformJumpskirtChiefEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
