- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Cluster
  - Kettle
  - Marathon
  - Omega
  - Moose
  - Origin
  - Meta
  - Barratry

- type: gameMapPool
  id: WhiteMapBox
  maps:
    - WhiteBox