- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  wikiLink: "https://wiki.ss14.su/%D0%93%D1%80%D1%83%D0%B7%D1%87%D0%B8%D0%BA"
  startingGear: CargoTechGear
  icon: "CargoTechnician"
  supervisors: job-supervisors-hop-qm
  access:
  - Cargo
  - Maintenance
  - External

- type: startingGear
  id: CargoTechGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  innerclothingskirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
