- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  wikiLink: "https://wiki.ss14.su/%D0%9A%D0%B2%D0%B0%D1%80%D1%82%D0%B8%D1%80%D0%BC%D0%B5%D0%B9%D1%81%D1%82%D0%B5%D1%80"
  requirements:
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 3600
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 15000
  weight: 10
  startingGear: QuartermasterGear
  icon: "QuarterMaster"
  supervisors: job-supervisors-hop
  whitelistedSpecies:
    - Human
    - Dwarf
  canBeAntag: true
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatQMsoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    pocket1: AppraisalTool
  innerclothingskirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
