- type: job
  id: Janitor
  name: job-name-janitor
  description: job-description-janitor
  playTimeTracker: JobJanitor
  wikiLink: "https://wiki.ss14.su/%D0%A3%D0%B1%D0%BE%D1%80%D1%89%D0%B8%D0%BA"
  startingGear: JanitorGear
  icon: "Janitor"
  supervisors: job-supervisors-hop
  access:
  - Janitor
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: GarbageDay
    prototype: WeaponRevolverInspector

- type: startingGear
  id: JanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitJanitor
    back: ClothingBackpackFilled
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHatPurplesoft
    id: JanitorPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  innerclothingskirt: ClothingUniformJumpskirtJanitor
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: JanitorMaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid
    back: ClothingBackpackFilled
    id: JanitorPDA
    head: ClothingHeadHatCatEars
    ears: ClothingHeadsetService
    belt: ClothingBeltJanitorFilled
  innerclothingskirt: ClothingUniformJumpskirtJanimaid
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
