- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  wikiLink: "https://wiki.ss14.su/%D0%9D%D0%B0%D1%83%D1%87%D0%BD%D1%8B%D0%B9_%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C"
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 27000
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "ResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  whitelistedSpecies:
    - Human
    - Dwarf
  canBeAntag: true
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLab
    id: RnDPDA
    ears: ClothingHeadsetRD
  innerclothingskirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
