- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  wikiLink: "https://wiki.ss14.su/%D0%A3%D1%87%D0%B5%D0%BD%D1%8B%D0%B9"
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 1800
  startingGear: ScientistGear
  icon: "Scientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    id: SciencePDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtScientist
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
