- type: job
  id: MedicalCyborg
  name: job-name-medical-cyborg
  description: job-description-cyborg
  playTimeTracker: JobCyborg
  icon: "MedicalDoctor"
  supervisors: "all crew"
  canBeAntag: false
  jobEntity: PlayerCyborgMedical
  startingGear: CyborgGear # for char preview only
